CLOSE DATA
_zSafe=SET([SAFETY])
SET SAFETY OFF
SELE 0
use c:\SVM\data\av337s
ZAP
APPEN FROM c:\SVM\distrdat\av337s
use c:\SVM\data\avaircra
ZAP
APPEN FROM c:\SVM\distrdat\avaircra
use c:\SVM\data\avairtyp
ZAP
APPEN FROM c:\SVM\distrdat\avairtyp
use c:\SVM\data\avbck337
ZAP
APPEN FROM c:\SVM\distrdat\avbck337
use c:\SVM\data\avcustom
ZAP
APPEN FROM c:\SVM\distrdat\avcustom
use c:\SVM\data\aveqdata
ZAP
APPEN FROM c:\SVM\distrdat\aveqdata
use c:\SVM\data\avinsptr
ZAP
APPEN FROM c:\SVM\distrdat\avinsptr
use c:\SVM\data\avlogstk
ZAP
APPEN FROM c:\SVM\distrdat\avlogstk
use c:\SVM\data\avwamast
ZAP
APPEN FROM c:\SVM\distrdat\avwamast
use c:\SVM\data\avphrase
ZAP
APPEN FROM c:\SVM\distrdat\avphrase
use c:\SVM\data\avwbfins
ZAP
APPEN FROM c:\SVM\distrdat\avwbfins
use c:\SVM\data\avwbfmtr
ZAP
APPEN FROM c:\SVM\distrdat\avwbfmtr
use c:\SVM\data\avwbfrem
ZAP
APPEN FROM c:\SVM\distrdat\avwbfrem
use c:\SVM\data\avwbrins
ZAP
APPEN FROM c:\SVM\distrdat\avwbrins
use c:\SVM\data\avwbrmtr
ZAP
APPEN FROM c:\SVM\distrdat\avwbrmtr
use c:\SVM\data\avwbrrem
ZAP
APPEN FROM c:\SVM\distrdat\avwbrrem
use c:\SVM\data\avwcmast
ZAP
APPEN FROM c:\SVM\distrdat\avwcmast
use c:\SVM\data\avwo_813
ZAP
APPEN FROM c:\SVM\distrdat\avwo_813
use c:\SVM\data\avqu_mtr
ZAP
APPEN FROM c:\SVM\distrdat\avqu_mtr
use c:\SVM\data\avqu_itm
ZAP
APPEN FROM c:\SVM\distrdat\avqu_itm
use c:\SVM\data\avqu_lbr
ZAP
APPEN FROM c:\SVM\distrdat\avqu_lbr
use c:\SVM\data\avqu_eqp
ZAP
APPEN FROM c:\SVM\distrdat\avqu_eqp
use c:\SVM\data\avqu_prt
ZAP
APPEN FROM c:\SVM\distrdat\avqu_prt
use c:\SVM\data\avqu_trd
ZAP
APPEN FROM c:\SVM\distrdat\avqu_trd
use c:\SVM\data\configav
ZAP
APPEN FROM c:\SVM\distrdat\configav
use c:\SVM\data\configlc
ZAP
APPEN FROM c:\SVM\distrdat\configlc
CLOSE DATA
SET SAFETY &_zSafe