CLOSE DATA
SELE 0
use C:\SVM\data\av337s
ZAP
APPEN FROM C:\SVM\testdata\av337s

SELE 0
use C:\SVM\data\avaircra
ZAP
APPEN FROM C:\SVM\testdata\avaircra

SELE 0
use C:\SVM\data\avairtyp
ZAP
APPEN FROM C:\SVM\testdata\avairtyp

SELE 0
use C:\SVM\data\avbck337
ZAP
APPEN FROM C:\SVM\testdata\avbck337

SELE 0
use C:\SVM\data\avcustom
ZAP
APPEN FROM C:\SVM\testdata\avcustom

SELE 0
use C:\SVM\data\aveqdata
ZAP
APPEN FROM C:\SVM\testdata\aveqdata

SELE 0
use C:\SVM\data\avinsptr
ZAP
APPEN FROM C:\SVM\testdata\avinsptr

SELE 0
use C:\SVM\data\avlogstk
ZAP
APPEN FROM C:\SVM\testdata\avlogstk

SELE 0
use C:\SVM\data\avwamast
ZAP
APPEN FROM C:\SVM\testdata\avwamast

SELE 0
use C:\SVM\data\avphrase
ZAP
APPEN FROM C:\SVM\testdata\avphrase

SELE 0
use C:\SVM\data\avwbfins
ZAP
APPEN FROM C:\SVM\testdata\avwbfins

SELE 0
use C:\SVM\data\avwbfmtr
ZAP
APPEN FROM C:\SVM\testdata\avwbfmtr

SELE 0
use C:\SVM\data\avwbfrem
ZAP
APPEN FROM C:\SVM\testdata\avwbfrem

SELE 0
use C:\SVM\data\avwbrins
ZAP
APPEN FROM C:\SVM\testdata\avwbrins

SELE 0
use C:\SVM\data\avwbrmtr
ZAP
APPEN FROM C:\SVM\testdata\avwbrmtr

SELE 0
use C:\SVM\data\avwbrrem
ZAP
APPEN FROM C:\SVM\testdata\avwbrrem

SELE 0
use C:\SVM\data\avwcmast
ZAP
APPEN FROM C:\SVM\testdata\avwcmast

SELE 0
use C:\SVM\data\avwo_813
ZAP
APPEN FROM C:\SVM\testdata\avwo_813

SELE 0
use C:\SVM\data\configav
ZAP
APPEN FROM C:\SVM\testdata\configav

SELE 0
use C:\SVM\data\configlc
ZAP
APPEN FROM C:\SVM\testdata\configlc

CLOSE DATA
